PollHistoryLimit:   3
TossupThreshold:    3.01
ECVAlgorithm:       2
PlotHeight:         10.0
PlotWidth:          10.0

# Poll History Limit (integer)
# Only look back this many polls or less.

# Tossup Threshold (float64)
# If the percentage difference is less than this threshold, its a tossup.

# ECV Algorithm (integer)

    # 1
    #
    # Tossup status is contingent on the difference, other total, and global.TossupThreshold.
    # If the percentage difference - the other percentage is under glob.TossupThreshold,
    # then the outcome is a tossup.

    # 2
    #
    # The other total is awarded proportionately to both candidates.
    # If the new totals have a difference below glob.TossupThreshold, then the outcome is a tossup.

# Plot height and width as a float64 quantity of postscript points (dots)
