PollHistoryLimit:   3
TossupThreshold:    3.01
ECVAlgorithm:       1
PlotHeight:         10.0
PlotWidth:          10.0

# PollHistoryLimit: Poll History Limit (integer)
# Only look back this many polls or less.

# TossupThreshold: Tossup Threshold (float64)
# If the percentage difference is less than this threshold, its a tossup.

# ECVAlgorithm: Electoral College Vote Allocation Algorithm (integer)

    # 1
    #
    # Which candidate has a higher poll percentage?
    # Is the difference below the tossup threshold?
    # Might the "Other" percentage make a difference in the future?


    # 2
    #
    # Split the "Other" percentage proportionally amongst the candidates. Then,
    # Which candidate has a higher poll percentage?
    # Is the difference below the tossup threshold?

# Plot height and width (float64)
# These are the height and width respectively, measured in the quantity of postscript points (dots)
