PollHistoryLimit:   3
TossupThreshold:    3.01
ECVAlgorithm:       2
PlotHeight:         10.0
PlotWidth:          10.0

# PollHistoryLimit: Poll History Limit (integer)
# Only look back this many polls or less.

# TossupThreshold: Tossup Threshold (float64)
# If the percentage difference is less than this threshold, its a tossup.

# ECVAlgorithm: Electoral College Vote Allocation Algorithm (integer)

    # 1
    #
    # Calculate the Other percentage = 100 - the sum of the Biden and Trump percentages.
    # Calculate DIFF = the absolute value of the difference between Biden and Trump percentages.
    # If DIFF minus the Other percentage is under the TossupThreshold, 
    #    then the outcome is a tossup.
    # Otherwise, determine the winner and ECV award.

    # 2
    #
    # Calculate the Other percentage = 100 - the sum of the Biden and Trump percentages.
    # The Other percentage is awarded proportionately to both candidates.
    # If the new Biden and Trump totals have a difference below the TossupThreshold, 
    #    then the outcome is a tossup.
    # Otherwise, determine the winner and ECV award.

# Plot height and width (float64)
# These are the height and width respectively, measured in the quantity of postscript points (dots)
